# Generated by Django 3.1.5 on 2021-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210217_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansinfo',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quesinfo',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
