# Generated by Django 3.1.5 on 2021-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210202_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='college_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
